WiseLibs/better-sqlite3

src/util/macros.h
Just applied the solution from here and checked that the project compiled without warnings and works: http://stackoverflow.com/questions/29355956/how-can-i-fix-error-code-c4146-unary-minus-operator-applied-to-unsigned-type-re
Resolves #9
=> Fix macros.h to support ia32 on Windows (#9)

src/util/macros.lzz
Found a small typo in the `TypeError` messaging.
=> Edit possible typo, "arguement" --> "argument"

test/23.statement.iterate.js
Another, unnamed sqlite node module fails a test just like this a large fraction of the time even with just 1000 rows. Rows just go missing.
`better-sqlite3` passes solidly with 1m rows.
Note that this test has a `runtime` const which I picked a value of a second, but that does mean this test suite takes 9 seconds rather than 7 seconds. Feel free to adjust as you see fit.
(Also, please consider adding `prettier`, it'd make matching your existing code a lot easier!)
=> Verify non-trivial batches of inserts are all persisted

deps/common.gypi
This adds support for building from source with VS2017 and VS2019. The latest versions of `node-gyp` have support for these now.
Solves #251
=> Add support for building in VS2019

deps/download.sh
This PR upgrades SQlite to 3.32.0.
Changelog and new features:
https://sqlite.org/releaselog/3_32_0.html
=> Upgrade to SQLite 3.32.0

binding.gyp
V8 has required C++14 since ~2017. It appears that changes in recent V8 versions (8.6+) have brought C++14 features into the parts of V8 that `better-sqlite3` builds against, causing native module compilation to fail. (I observed this when updating from Electron 10, which uses V8 8.5, to Electron 11, which uses V8 8.7.) Updating to the C++14 standard resolves this issue and gets `better-sqlite3` building again.
Resolves #494.
=> Adopt C++14

lib/util.js
Fixes #414 
When running https://github.com/pelotom/better-sqlite3-jest-bug against this patch, we can see that the error is gone and memory stays constant:
=> Fix monkey patching bug + memory leak when running in Jest

.travis.yml
Based on the following release announcement
https://www.electronjs.org/releases/stable#12.0.0
https://www.electronjs.org/releases/stable#end-of-support-for-9xy
=> [Electron] Add support for 12.x, drop 9.x (EOL)

docs/threads.md
This is an update to the `master.js` used in worker threads example.
The if condition that checks for pending jobs wrapped in the `poll()` function creates an infinite loop by calling itself using `setImmediate(poll)` when the job queue is empty. This creates a massive unnecessary workload for one or many cores in the CPU. _([Comment](https://github.com/JoshuaWise/better-sqlite3/issues/237#issuecomment-782276920) in #237 )_
```js
function poll() {
if (queue.length) {
// If there's a job in the queue, send it to the worker
job = queue.shift();
worker.postMessage(job.message);
} else {
// Otherwise, check again later
timer = setImmediate(poll); <- Gets looped infinitely if the queue has no jobs
}
}
```
Get rid of the `setImmediate(poll)` completely and introduce a function that schedules …
=> Fix the infinite loop created by setImmediate() in threads example

.github/workflows/build.yml
This PR adds support for Electron 13, which was released last week.
Electron 10 is now End-of-Life if you'd like to drop support. (I figured that was a more significant change though, so I left it out of this PR.)
=> Generate prebuilds for Electron 13

.github/workflows/build.yml
This fixes the following issues:
- Broken prebuild linux packages for anything < Ubuntu 20.04, Debian 11, and more
- Running Electron apps on any OS < Ubuntu 20.04, and Debian 11
- Unable to install better-sqlite3 on those OSs
This causes _no_ compatibility issues with later versions of GLIBC, so all new OSes work just fine. I have confirmed this on Ubuntu 20.04 using a package built on 18.04. It should be a set and forget fix.
This took some real sleuthing to figure out for my app. Hope this helps others!
Workaround until this is merged: Downgrade to `7.1.2`, as this was built on 18.04 before Github changed `ubuntu-latest` build images to 20.04 instead of 18.04
Fix #586
Fix #403
=> Fixes GLIBC 2.29 issues, electron issues, and more

binding.gyp
Add linker flags to
- prevent the dynamic linker from using an external SQLite for this
library (`-Bsymbolic`) and
- prevent the dynamic linker from using the internal SQLite for other
libraries (`--exclude-libs ALL`).
This is just a (conflict-free) cherry-pick of a Signal-specific fix in
https://github.com/signalapp/better-sqlite3/pull/3 that seems OK to upstream further.
=> Encapsulate the internal SQLite

package.json
Fixes #713, #694.
`electron-builder` uses a dependency named [`app-builder`](https://github.com/develar/app-builder) that uses whatever version of `prebuild-install` used by the project simply as a peer dependency. So this simple update will fix the issues related to installing pre-built binaries for newer versions of Electron (14.x, 15.x, 16.x).
For the moment, users can run `npm install -D prebuild-install@latest` on the root project and fix the issue.
=> Update `prebuild-install` to `v7.0.0`

.github/workflows/build.yml
Arm64 is getting more and more popular with the oracle servers and raspberry pi's so it would be great to have prebuilds for it.
Could have probably added arm64 support for other builds too but didn't want to start testing if they actually work.
=> add arm64 prebuilds for alpine

.github/workflows/build.yml
Using properties from `github.event.repository` instead of hardcoded repo URLs and names will prevent the job from being broken in the slight chance of this repo being [moved to an organization](https://github.com/JoshuaWise/better-sqlite3/pull/724#issuecomment-974501165) in the future. It's safer even if the redirects are set.
=> Use `github` context properties in `arm64-alpine` prebuild job

.github/workflows/build.yml
Stable Electron `v17.0.0` was just released. `node-abi` parses the newly released version just fine. Successful build log available [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/runs/5016727829?check_suite_focus=true#step:5:81).
=> Add support for electron `v17` prebuilds

.github/workflows/build.yml
This PR adds multiple new features and improvements.
- Added `armv7` prebuilt binaries for Alpine
- Added both `armv7` and `arm64` prebuilt binaries for Linux (very useful for Raspbian users)
- All the jobs that runs on Qemu containers now uses `checkout` action which supports correct trigger `ref`
- Added `publish` job completion requirement to all jobs
As always, all these changes were tested on multiple releases, for weeks at [`better-sqlite3-multiple-ciphers`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/blob/master/.github/workflows/prebuild.yml).
=> Add Linux prebuilt binaries for `armv7` and `arm64` and other improvements

.github/workflows/update-sqlite.yml
This PR creates a new workflow dedicated for the process of updating SQLite.
The thought behind this addition is that it seems much easier and cleaner in regards of both safety with binary files and wide testing. Just thought of creating this since the topic of safety was brought up by @JoshuaWise recently in a PR conversation.
The workflow is manually dispatched and presents you with the following prompt which are also the variables needed for the download script.
🟢 This PR does not break the current manual update flow. In fact as seen in the diff, it's done without changing a single line of code in the download script.
🟢 Instead of directly pushing the changes, this workflow will do the changes on a new branch and an automated pull request will be created from that branch which will …
=> Automate the process of updating SQLite version

.github/workflows/build.yml
**Notes:**
- Ubuntu image for tests has been changed to `ubuntu-20.04` since Node v18 requires GLIBC 2.28
**Thoughts:**
- Ubuntu image for the builds can also be changed _(not exactly necessary)_ but issue #403 still prevents that. However it's possible to build just the Node v18 prebuilds on `ubuntu-20.04` if required.
=> Add support for Node `v18` prebuilds

package.json
This PR ensures _(even though all semver patches are already accepted for `prebuild`)_ that Electron headers are properly pulled in the build process for newer Electron versions, since https://github.com/prebuild/prebuild/pull/292 is now merged and included in v11.0.4.
This PR will also allow #834 to be merged. 
- [A successful test build for reference](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/2678671957)
=> Update `prebuild` dependency to v11.0.4

.github/workflows/build.yml
This PR adds support for building prebuilt binaries for Electron v19.x.y.
_**Note:**_
I highly recommend holding off on merging this PR till https://github.com/prebuild/prebuild/pull/292 is merged and `prebuild` version used in BS3 is bumped since starting from Electron v19, prebuild script [will fail](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/runs/7163185059?check_suite_focus=true#step:5:12) at downloading headers.
=> Add support for electron `v19` prebuilds

src/better_sqlite3.cpp, src/better_sqlite3.hpp, src/util/custom-table.lzz, test/34.database.table.js
This PR add limit and offset clause support for user-defined virtual tables.
Fix #872.
=> Fix virtual table limit offset

package.json
This ensures compatibility with all package manager installation choices.
Closes #893.
=> Remove `npm run` from `install` lifecycle script.

README.md
The performance difference can be several orders of magnitude on even simple tables, and most users won't think to go looking for this.
I've included lines that clarify, and link to your existing documentation on the topic.
Thank you for an excellent tool.
=> Please consider setting pragma WAL in your introductory documentation

.github/workflows/build.yml
Electron v21 is the latest stable. Prebuilds are tested against module version 109.
=> Add support for electron `v21` prebuilds

package.json
This fixes 1 moderate and 2 high severity vulnerabilities (according to `npm audit`).
=> Upgrade mocha: 8 → 10

.github/workflows/build.yml, docs/troubleshooting.md
The current version of better-sqlite3 seems to be compatible with the latest Node 19, which is great news! This PR adds it to the list of node versions tested in the build workflow, and in the list of recommended versions in the troubleshooting docs. This does add a job run to the `test` job. 
Small flag also that [Node 14 is going end of life next month](https://nodejs.org/en/blog/announcements/v19-release-announce/), so maybe we don't want to keep explicitly testing it after that?
=> Explicitly support node 19

.github/workflows/update-sqlite.yml
The latest version of the `repo-sync/pull-request` (v2) action parses template text differently.
Previously backticks had to be escaped, but not anymore. Backslashes are removed so the backticks won't be parsed as literals in the PR body, as seen in the following screenshot.
=> Fix `pr_body` text of `update-sqlite` workflow

.github/workflows/build.yml
Stable Electron v24 has just been released. Prebuild process was [tested](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/4621541317).
=> Add support for electron `v24` prebuilds

.github/workflows/build.yml
This change is necessary since GitHub has dropped support for the `ubuntu-18.04` image. (https://github.com/actions/runner-images/issues/6002)
This will also mean that Linux distributions with only glibc version `2.29` and above will be supported by the prebuilt binaries.
=> Change Linux runner image to `ubuntu-20.04`

.github/workflows/build.yml
It's unnecessary to have the same, base build command fully written for each job.
=> Move repetitive build commands into environment variables

.github/workflows/build.yml
#989 was broken by the additional commit https://github.com/mceachen/better-sqlite3/commit/a99e3d3e844dd492e45c67778393d249d0a18c9b and this PR contains the fix from @mceachen.
I somehow didn't notice the error when merging that branch with the original PR branch. Oh well 🤷🏽.
BTW @mceachen, your fix branch is apparently sourced from https://github.com/WiseLibs/better-sqlite3/commit/f190fefc9959cf6806b0bec5f3e57df508e1d573, hence the conflict. But I went ahead and merged it anyway since you requested to do so. I'm guessing you aren't able to approve your own revert either.
=> Fix the build workflow broken by #989

.github/workflows/build.yml
Future Node LTS release, at the moment current release.
=> Add support for Node v20 prebuilds

.github/workflows/build.yml
Node v14 just reached EOL. This would be a proactive measure to avoid getting bombarded with build errors in future builds. This would also make tests and builds finish quicker. Not vital to test against a runtime that isn't actively supported anymore.
I've also removed the quite unnecessary non-LTS tests for Node v19 _(which also will soon reach EOL)_.
=> Remove node.js v14 builds and tests (runtime EOL)

src/better_sqlite3.cpp, src/better_sqlite3.hpp, src/objects/statement.lzz, test/13.database.prepare.js
Fixes #975
I would love to include a regression test with this PR, but as the problem only occurs when reading random noise past the end of a string, I have no idea how to accomplish such a feat.
=> Fix out-of-bounds read in statement tail parser

.github/workflows/build.yml
Stable electron `v26` just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/5864358650).
=> Add support for electron `v26` prebuilds

src/better_sqlite3.cpp, src/objects/database.lzz, src/util/macros.lzz
This is a fix for #981
It use a #ifdef encapsulation to only use the copy method on electron build.
This is the first time I use lzz and I did not achieve to output #ifndef/else/endif clause from the database.lzz file, so I use the macro.lzz instead. I hope this is acceptable :).
=> Fix db::serialize() crashing with Electron

deps/copy.js
For various complicated reasons, I have to build `better-sqlite3` with an empty `build/Release` folder. If that's the case, `copy.js` will fail to create directories before attempting to copy files, which will in turn fail.
This PR ensures that we create target directories before copying files.
=> Fix: Create target directory when copying  

docs/api.md
Fixes https://github.com/WiseLibs/better-sqlite3/issues/1007
=> fix result code type in SQliteError documentation

package.json
Since prebuild has updated it's dependency to the latest node-gyp version 9.4.0, the version override may no longer be required.
=> update prebuild and remove node-gyp version override

.github/workflows/build.yml
Node `v16` reached its EOL today. It's better not to build for unsupported runtimes on future releases.
This also removes building for Electron versions that ship with Node `v16`. This might seem a bit extreme but this limits a lot of issues in building going forward _(like we faced in the past)_. It also significantly reduces the build time in releases. It already feels too much.
=> Stop building and testing against Node `v16` (runtime EOL)

.github/workflows/build.yml
Stable electron v28 just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7093233455).
=> Add support for electron `v28` prebuilds

.github/workflows/build.yml
Now that [GitHub officially has an M1 macOS runner](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) available, it's much better to build arm builds natively on the `macos-14` runner. Results in way faster and much more stable builds. Completes in about 4 minutes compared to the previous 10 minutes. All of the prebuilds currently supported by BS3 were tested on this runner at [`better-sqlite3-multiple-ciphers`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers).
- [**Node build logs**](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7807635689/job/21296387383)
- [**Electron build logs**](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7807640326/job/21296402646) …
=> Build `arm` based macOS builds natively

.github/workflows/build.yml
This seems to be becoming a necessity now since Windows is getting popular on arm64 devices.
All of the supported runtime versions were tested at [`better-sqlite3-multiple-ciphers` (successful workflow run)](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7853495517).
🟡 As seen in the diff, Node arm64 build needed a custom command since there aren't any official Windows arm64 headers available for Node till Node v20 (https://nodejs.org/dist/v20.0.0). So for the moment, we can only build against Windows arm64 for Node v20 upwards. We can clean up the build process once Node v18 has reached EOL.
=> Add support for Windows `arm64` prebuilds

.github/workflows/build.yml
Stable electron v29 just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7969186491) but the tests are failing with the following error.
```
D:\better-sqlite3\build\src\util\macros.lzz(150,33): error C2664: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,
v8::Local<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)': cannot convert argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute' [D:\better-sqlite3\build\better_sqlite3.vcxproj]
```
Pinging @JoshuaWise.
=> Add support for electron `v29` prebuilds

.github/workflows/build.yml
This is a rollback PR for the changes from #1147, till the build errors are fixed.
=> Temporarily disable builds for electron `v29`

.github/workflows/build.yml, package.json, src/better_sqlite3.cpp, src/better_sqlite3.hpp, src/util/macros.lzz
This branch adds some adjustments in order to enable builds for Electron v29. The signature of ```SetAccessor``` has been adjusted to be the same as before for all versions below 29. For 29 and up the new function signature will be used.
=> Support builds for Electron v29

docs/api.md
I spent two hours reading the SQLite documentation and the better-sqlite3 source code. Thought this might help other people as well.
Thanks for the great library!
=> Clarify error handling behavior for nested transactions in docs

.github/workflows/build.yml
Stable electron v30 just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/8699810421).
=> Add support for electron `v30` prebuilds

.github/workflows/build.yml
@JoshuaWise this should fix the current build failure on `master`.
Fixes https://github.com/WiseLibs/better-sqlite3/actions/runs/8853339888/job/24313966887
1. the `if` clauses didn't capture `macos-latest` and `macos-14` properly
2. let's use `brew install python-setuptools` instead of `--break-system-packages`.
NOTE: it'd be ideal if we could extract this as a setup task to eliminate the code duplication here, but I didn't want to make the diff bigger. Holler if you'd prefer that.
=> Fix python setuptools on macOS

.github/workflows/build.yml, .github/workflows/bump-version.yml, .github/workflows/update-sqlite.yml
We've got a ton of ancient versions in here, and we're building on a version of Node.js that EOL'ed more than 6 months ago.
I've culled versions that EOL'ed more than 6 months ago, which should speed up build times. I also added Node.js v22.
This PR requires the next build be a major version.
=> Add Node.js v22. Drop ancient EOL versions of Node.js and Electron

test/10.database.open.js
This test has been flaky on several recent builds: see https://github.com/WiseLibs/better-sqlite3/actions/runs/9307316024/job/25618338129?pr=1191#step:9:417
=> Relax allowed timeout (GHA on macOS is slow)

.github/workflows/build.yml, src/better_sqlite3.hpp, src/util/macros.lzz
Replaced deprecated v8::CopyablePersistentTraits with v8::Global to enabled builds for Electron v31.
=> Support builds for Electron v31

.github/workflows/build.yml
The `macos-latest` runner label has [been migrated](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) to `macos-14` which means the build workflow will try to build for ARM64 macs twice. This will restore the previous build process.
=> Fix macOS x64 builds

.github/workflows/build.yml
This will downgrade the used GLIBC to v2.31, so it's again compatibe with ubuntu 20.04.
- #990
=> Use node bullseye to build arm images

.github/workflows/build.yml, binding.gyp, src/better_sqlite3.cpp, src/better_sqlite3.hpp, src/util/macros.lzz
With the release of Electron v32 some classes and functions marked as deprecated have been removed and require adjustments. Also c++20 is now required by v8.
=> Support builds for Electron v32

.github/workflows/build.yml
Added prebuild for Electron 32.0.0.
=> Prebuild for Electron 32

.github/workflows/build.yml
This pull request adds prebuild artifacts for electron linux/arm64
=> feat: add linux/arm64 prebuilds for electron

docs/threads.md
The Node.js documentation states that `os.cpus()` should not be used to calculate the amount of threads an app should launch because CPU information might be unavailable ([source](https://nodejs.org/api/os.html#oscpus)).
In Node.js v19.4.0 and v18.14.0, `os.availableParallelism()` was added for that purpose.
=> Update thread count calculation method in worker_threads example

.github/workflows/build.yml
Stable electron v35 just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/13659710463).
=> Add support for electron `v35` prebuilds

.github/workflows/build.yml
This is a necessary update since the `ubuntu-20.04` runner will be [fully unsupported by the 1st of April](https://github.com/actions/runner-images/issues/11101).
Builds might run into issues and the build artifacts might not be fully compatible with some older distros _(`glibc` fiasco)_. Guess we're gonna have to test and debug.
=> Update the Ubuntu runner image in build script to `ubuntu-22.04`

.github/workflows/build.yml
This fixes #1348 by building the artifacts on a base Linux image with `glibc` 2.31.
I still don't like this because the build script has become a mess trying to keep backward compatibility alive. It's pretty difficult to maintain now. But there's no alternative I guess. 🤷🏻‍♂️
Here's a test artifact built using this container for reference. It's for Node v22. I suggest testing this.
[better-sqlite3-v11.9.0-node-v127-linux-x64.tar.gz](https://github.com/user-attachments/files/19298714/better-sqlite3-v11.9.0-node-v127-linux-x64.tar.gz)
**Side note:**
Now that [native arm Linux runners are available](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/), we can switch to them for much faster testing and building. I …
=> Use the `node:18-bullseye` image for Linux x64 builds

lib/methods/transaction.js
As described in https://github.com/WiseLibs/better-sqlite3/issues/319:
> You should never keep SQLite3 transactions open across event loop ticks in Node.js. SQLite3 serializes all statements/transactions. This means, if you try to run an asynchronous function within an SQL statement, you'll block all other statements/transactions across your entire program. better-sqlite3 doesn't support it, and it never will, because it's a very bad idea.
This is reasonable. **But**: Currently if a user passes an async function as a transaction callback, the resulting behaviour is very confusing and **dangerous**: It will run the first statement within the transaction, commit the transaction, and then the other part of the async function will run at a random time later without any transaction context, …
=> Disallow transaction to return a Promise due to unexpected behaviour

docs/benchmark.md
This PR updates the repository URL at `benchmark.md` to the current project's path.
* [`docs/benchmark.md`](diffhunk://#diff-3d312199f1da21c13b99d654a88a249129c2d8d05712a224085c98f16ff19315L6-R6): Updated the repository URL from `https://github.com/JoshuaWise/better-sqlite3.git` to `https://github.com/WiseLibs/better-sqlite3.git`.
=> docs: fix clone url at benchmark.md

.github/workflows/build.yml, .github/workflows/bump-version.yml, .github/workflows/update-sqlite.yml, package.json
- Node v18 has been EOL for a couple weeks
- I dropped Electron versions that have been EOL for over a year
- I added an engines clause to fix #1344
- I added Node v24 which just released.
I haven't done any verification of this branch. We'll see how GHA likes it.
=> BREAKING CHANGE: drop EOL Node.js v18 and Electron v26, v27, and v28. Add node v24 to build matrix.

src/better_sqlite3.cpp, src/util/macros.lzz
Electron switched to using v8's sandboxing feature as of V21. With this enabled, allocating a buffer using `node::Buffer::New` crashes the program, because it attempts to allocate memory outside of the allowed memory address range of the sandbox.  
```
[23992:0508/184214.301:ERROR:node_bindings.cc(162)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers, or disable the sandbox.
```
Reproducing the issue is as simple as calling `db.serialize()` in Electron versions 30.0 and higher.
PR #1036 fixed this for electron versions until 30.x.x+, where this fix broke. Why this only broke in the most recent Electron …
=> Use correct flag to determine if V8 Sandboxing is enabled

.github/workflows/build.yml
Stable electron v37 just released. Prebuilds were tested [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/15842767163).
=> Add support for electron `v37` prebuilds

.github/workflows/build.yml
The support for `windows-2019` runner has [officially been dropped](https://github.com/actions/runner-images/issues/12045). IIRC, we only kept the `windows-2019` runner to continue building for Node `v16`, which has also been EOL for some time now.
This PR updates the Windows runner on all workflow jobs to `windows-2022`. Successful tests can be seen [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/16024127041) and [here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/16024279545).
=> Update the Windows runner on build workflow to `windows-2022`

benchmark/drivers.js, benchmark/index.js, benchmark/types/insert.js, benchmark/types/select-all.js, benchmark/types/select-iterate.js, benchmark/types/select.js, benchmark/types/transaction.js
This adds a benchmark for the built-in [node:sqlite](https://nodejs.org/api/sqlite.html) module available with `--experimental-sqlite` since Node v22.5.0.
This benchmark will only run and be included in the results if the `node:sqlite` module exists and is available.
Known issues:
1) This creates prepared statements for every query instead of reusing persistent statements because [DatabaseSync.prepare](https://nodejs.org/api/sqlite.html#databasepreparesql) is a wrapper for `sqlite3_prepare_v2` that doesn't accept `SQLITE_PREPARE_PERSISTENT` flag.
2) Iterate benchmark does nothing for now as [StatementSync.iterate](https://nodejs.org/api/sqlite.html#statementiteratenamedparameters-anonymousparameters) was added in Node v23.4.0 but even after updating it fails with "statement has been …
=> Add node:sqlite benchmark

package.json
With the deprecation and removal of lzz, the glob pattern for the files to include in the package is too narrow. Adjusted the pattern to include all files below src.
=> Include all source files in package
