src/binder/bind-object.cc
src/multi-binder/bind-object.cc
src/objects/database/create-statement.cc
src/objects/database/create-transaction.cc
src/objects/database/database.cc
src/objects/database/pragma.cc
src/objects/int64/int64.cc
src/objects/statement/each.cc
src/objects/statement/statement.cc
src/objects/statement/util.cc
src/objects/transaction/transaction.cc
src/objects/transaction/util.cc
src/util/bind-map.h
src/util/data.cc
src/util/macros.h
src/util/sql-rope.h

Improves the performance of creating transactions

implemented a more efficient string join

---

docs/troubleshooting.md

Taken from https://github.com/JoshuaWise/better-sqlite3/issues/170#issuecomment-441734343
(I created this PR after seeing N more "I can't install on windows" issues get opened)

Add windows installation instructions

---

package.json

(why don't you want a `yarn.lock` or `package-lock.json`?)

Housekeeping: upgrade dependencies

---

.travis.yml

Add node v12 and drop node v9 from Travis

---

deps/test_extension.c
test/34.database.load-extension.js
test/42.integrity.js

I updated the test_extension.c to export the init function for Windows.  I also updated the tests, now all the load extension tests are working on Windows.

Window test extension

---

.travis.yml

Add node 14 to prebuild

---

.travis.yml

I am not sure all versions are required since 4.x.x but we should certainly have more recent versions of electron on the list

Include latest electron versions

---

docs/troubleshooting.md

The old guide do not work anymore, update the guide to latest toolchain.

fix the installing guide for Windows

---

.github/workflows/npm-publish.yml
.github/workflows/prebuild.yml

It would be easier to do the CI in Github Workflows. As well as it supports both win & linux workers.

ci: added github workflows for prebuild and release

---

docs/api.md

Fix typo in API docs

---

docs/troubleshooting.md

This comes up frequently
See https://github.com/JoshuaWise/better-sqlite3/issues/609#issuecomment-829013505

Update node-gyp troubleshooting

---

.github/workflows/build.yml

Adding to prebuilds since stable Electron `v16.0.0` just released.

Add electron `v16` prebuild support

---

.github/workflows/build.yml

Makes it much easier to manually run tests against any branch on forks.

Add `workflow_dispatch` trigger for tests

---

README.md

It's much harder to track down the expected syntax than one would want.  Could we just toss a note in?

Add an example using `import` in Typescript

---

.github/workflows/build.yml

Stable Electron v22 was just released. Prebuilds are tested.

Add support for electron `v22` prebuilds

---

.github/workflows/build.yml

Stable Electron v23 was just released. Prebuilds are tested. ✅

Add support for electron `v23` prebuilds

---

.github/workflows/build.yml

Stable Electron `v25` was just released.

Add support for electron `v25` prebuilds

---

.github/workflows/build.yml

See https://github.com/WiseLibs/better-sqlite3/issues/1093#issuecomment-1783374614 and https://github.com/nodejs/node-gyp/issues/2915

Fix macOS and future Alpine prebuilds

---

.github/workflows/build.yml

* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-node/releases

Upgrade GitHub actions/checkout and actions/setup-node

---

.github/workflows/build.yml

Implementation of this discussion: https://github.com/WiseLibs/better-sqlite3/issues/1186#issuecomment-2140780678

Run prebuilds before publish

---

.github/workflows/build.yml

Following the example of #1242, this PR should add support for electron v33.

Prebuild for Electron 33

---

.github/workflows/build.yml

Added NodeJS 23 to build and test matrix.
fixes https://github.com/WiseLibs/better-sqlite3/issues/1281

Added NodeJS 23 Support

---

.github/workflows/build.yml

This pull request fixes the electron prebuild for linux/arm.

fix: electron prebuilds on linux arm

---

.github/workflows/build.yml
package.json

Added prebuild for Electron 34.0.0.

Prebuild for Electron 34

---

docs/api.md

Per https://github.com/WiseLibs/better-sqlite3/issues/356#issuecomment-2567128371

Add API doc note about statement finalization

---

README.md

See: https://github.com/WiseLibs/better-sqlite3/discussions/1277

README: add section on Upgrading

---

docs/api.md

"you might except..." => "you might expect".

Fix small typo in api.md

---

.github/workflows/build.yml

Add Electron 36 to prebuilt binaries.

Prebuild for Electron 36

---

.github/workflows/build.yml
package.json

Add Electron 38 to prebuilt binaries.

Prebuild for Electron 38
